name: sample-nuxtjs
services:
  - build_command: yarn build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: trondulseth/sample-nuxtjs
    name: sample-nuxtjs
